# Generated by Django 2.1.4 on 2018-12-04 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleLista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleTienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreLista', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('nombreTienda', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombreSucursal', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nomUsuario', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('contrasenia', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='lista',
            name='nombreUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Usuario'),
        ),
        migrations.AddField(
            model_name='detalletienda',
            name='idProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Producto'),
        ),
        migrations.AddField(
            model_name='detalletienda',
            name='nombreTienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Tienda'),
        ),
        migrations.AddField(
            model_name='detallelista',
            name='idLista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Lista'),
        ),
        migrations.AddField(
            model_name='detallelista',
            name='idProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Producto'),
        ),
    ]
