# Generated by Django 2.1.3 on 2018-12-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detalletienda',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
